import { useEffect, useMemo, useState } from 'react'

const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
export function MonthCalendar({value,onChange,highlightedDates,mutedDates=new Set(),mutedWeekdays=new Set(),mutedDateReasons=new Map(),mutedWeekdayReasons=new Map()}:{value:string;onChange:(date:string)=>void;highlightedDates:Set<string>;mutedDates?:Set<string>;mutedWeekdays?:Set<number>;mutedDateReasons?:Map<string,string>;mutedWeekdayReasons?:Map<number,string>}) {
  const selected=new Date(`${value}T12:00:00`)
  const[month,setMonth]=useState(()=>new Date(selected.getFullYear(),selected.getMonth(),1))
  useEffect(()=>setMonth(new Date(selected.getFullYear(),selected.getMonth(),1)),[value])
  const days=useMemo(()=>{const result:(Date|null)[]=Array((month.getDay()+6)%7).fill(null);for(let day=1;day<=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();day++)result.push(new Date(month.getFullYear(),month.getMonth(),day));return result},[month])
  const selectedReason=mutedDateReasons.get(value)??mutedWeekdayReasons.get(selected.getDay())
  return <section className="month-calendar"><header><button type="button" aria-label="Prethodni mesec" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString('sr-Latn-RS',{month:'long',year:'numeric'})}</strong><button type="button" aria-label="Sledeći mesec" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></header><div className="month-weekdays">{['Po','Ut','Sr','Če','Pe','Su','Ne'].map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{days.map((date,index)=>{if(!date)return <span key={`blank-${index}`}/>;const dateIso=iso(date);const reason=mutedDateReasons.get(dateIso)??mutedWeekdayReasons.get(date.getDay());const muted=mutedDates.has(dateIso)||mutedWeekdays.has(date.getDay());return <button type="button" key={dateIso} aria-label={reason?`${date.getDate()}, ${reason}`:muted?`${date.getDate()}, neradan dan`:undefined} className={`${dateIso===value?'selected ':''}${highlightedDates.has(dateIso)?'highlighted ':''}${muted?'muted':''}`} onClick={()=>onChange(dateIso)}>{date.getDate()}<i/></button>})}</div>{selectedReason&&<p className="calendar-closure-reason" role="status">{selectedReason}</p>}</section>
}
