services:
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: fm_dbuser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fm
        ports:
            - "8877:5432"
        # volumes:
        #     - ./postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        container_name: redis-server
        ports:
            - "6379:6379"