import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { errorMessage, forgotPassword, register, resetPassword } from '../api/client'

const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

export function AccountFlowPage({mode}:{mode:'register'|'forgot'|'reset'}){
 const location=useLocation();const navigate=useNavigate();const params=new URLSearchParams(location.search)
 const registrationKey=params.get('key')?.trim()??''
 const invalidRegistrationLink=mode==='register'&&!uuidPattern.test(registrationKey)
 const[key,setKey]=useState(params.get('resetKey')??'');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('')
 const title=mode==='register'?'Dovrši registraciju':mode==='forgot'?'Zaboravljena lozinka':'Postavi novu lozinku'
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode!=='forgot'&&password!==confirm){setError('Lozinke se ne poklapaju.');return}setBusy(true);try{if(mode==='register')await register(registrationKey,password);else if(mode==='forgot')await forgotPassword(email);else await resetPassword(key,password);setMessage(mode==='forgot'?'Ako nalog postoji, instrukcije su poslate emailom.':'Lozinka je uspešno postavljena. Možete se prijaviti.');if(mode!=='forgot')setTimeout(()=>navigate('/login'),1200)}catch(x){setError(errorMessage(x))}finally{setBusy(false)}}
 return <main className="login-page"><section className="login-story"><div className="brand-mark"><span>FM</span> Fitness Manager</div><div className="story-copy"><p className="eyebrow">Bezbedan pristup</p><h1>{mode==='forgot'?'Vrati se svom nalogu.':'Tvoj trening počinje ovde.'}</h1><p>Aktivacija i oporavak naloga koriste jednokratni ključ sa ograničenim rokom važenja.</p></div></section><section className="login-panel">{invalidRegistrationLink?<div className="login-form account-link-error" role="alert"><p className="eyebrow">Neispravan link</p><h2>Aktivacioni link nije važeći</h2><p className="muted">Link ne sadrži ispravan registracioni ključ. Otvorite originalni link iz aktivacionog emaila ili zatražite novi poziv od menadžera.</p><Link className="primary-button" to="/login">Nazad na prijavu <span>→</span></Link></div>:<form className="login-form" onSubmit={submit}><p className="eyebrow">Nalog</p><h2>{title}</h2><p className="muted">{mode==='forgot'?'Unesite email adresu naloga.':mode==='register'?'Aktivacioni link je potvrđen. Postavite lozinku za svoj nalog.':'Ključ je automatski preuzet iz linka; možete ga uneti i ručno.'}</p>{mode==='forgot'?<label>Email<input required value={email} onChange={e=>setEmail(e.target.value)}/></label>:<>{mode==='reset'&&<label>Reset ključ<input required value={key} onChange={e=>setKey(e.target.value)}/></label>}<label>Nova lozinka<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Potvrda lozinke<input required minLength={6} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">{message}</div>}<button className="primary-button" disabled={busy}>{busy?'Slanje…':'Potvrdi'} <span>→</span></button><small className="secure-note"><Link to="/login">Nazad na prijavu</Link></small></form>}</section></main>
}
