import { useEffect, useState } from 'react'
import { appointmentsApi } from '../api/appointments'
import { errorMessage } from '../api/client'
import { useAuthStore } from '../auth/authStore'
import type { AppointmentSummary } from '../types'

const future=(a:AppointmentSummary)=>new Date(`${a.date}T${a.startTime}`)>new Date()
const dateLabel=(a:AppointmentSummary)=>new Date(`${a.date}T12:00`).toLocaleDateString('sr-Latn-RS',{weekday:'short',day:'2-digit',month:'short'})
function AppointmentCard({appointment,action,actionLabel,disabled}:{appointment:AppointmentSummary;action?:()=>void;actionLabel?:string;disabled?:boolean}){return <article className="appointment-card"><div className="appointment-date"><strong>{dateLabel(appointment)}</strong><time>{appointment.startTime.slice(0,5)}–{appointment.endTime.slice(0,5)}</time></div><div><h3>{appointment.session.type==='INDIVIDUAL'?'Individualni trening':'Grupni trening'}</h3><p>{appointment.trainer?.email??'Trener još nije dodeljen'} · {appointment.room?.name??'Sala nije dodeljena'}</p><small>{appointment.clients.length}/{appointment.session.maxParticipants} rezervisanih mesta</small></div>{action&&<button className="secondary-button" disabled={disabled} onClick={action}>{actionLabel}</button>}</article>}
export function AppointmentsPage(){const role=useAuthStore(s=>s.session?.activeRole);const trainer=role==='TRAINER';const[mine,setMine]=useState<AppointmentSummary[]>([]);const[open,setOpen]=useState<AppointmentSummary[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState<number|null>(null);async function load(){try{const [owned,market]=await Promise.all([appointmentsApi.mine(),appointmentsApi.withoutTrainer()]);setMine(owned);setOpen(market)}catch(x){setError(errorMessage(x))}}useEffect(()=>{if(trainer)void load()},[trainer]);async function act(id:number,fn:()=>Promise<unknown>){setBusy(id);setError('');try{await fn();await load()}catch(x){setError(errorMessage(x))}finally{setBusy(null)}}if(!trainer)return null;const upcoming=mine.filter(future).sort((a,b)=>a.date.localeCompare(b.date)||a.startTime.localeCompare(b.startTime));const history=mine.filter(a=>!future(a));return <main className="workspace-page appointments-page"><header className="workspace-header"><div><p className="eyebrow">Trenerski portal</p><h1>Moji termini</h1><p>Pregledajte svoj angažman i preuzmite slobodne termine iz ponude.</p></div></header>{error&&<div className="content-error">{error}<button onClick={()=>setError('')}>×</button></div>}<section className="appointment-section"><div className="card-head"><div><p className="eyebrow">Sledeće</p><h2>Predstojeći termini</h2></div><strong>{upcoming.length}</strong></div><div className="appointment-list">{upcoming.map(a=><AppointmentCard key={a.id} appointment={a} action={()=>void act(a.id,()=>appointmentsApi.unassign(a.id))} actionLabel={busy===a.id?'Otkazujem…':'Otkaži dodelu'} disabled={busy!==null}/>)}{!upcoming.length&&<div className="empty-panel">Nemate budućih termina.</div>}</div></section><section className="appointment-section marketplace"><div className="card-head"><div><p className="eyebrow">Marketplace</p><h2>Termini bez trenera</h2></div><strong>{open.length}</strong></div><div className="appointment-list">{open.map(a=><AppointmentCard key={a.id} appointment={a} action={()=>void act(a.id,()=>appointmentsApi.assign(a.id))} actionLabel={busy===a.id?'Preuzimam…':'Preuzmi termin'} disabled={busy!==null}/>)}</div></section><section className="appointment-section muted-section"><div className="card-head"><div><p className="eyebrow">Arhiva</p><h2>Održani termini</h2></div><strong>{history.length}</strong></div><div className="appointment-list compact">{history.map(a=><AppointmentCard key={a.id} appointment={a}/>)}</div></section></main>}
