import { useEffect, useRef, useState, type FormEvent } from 'react'
import { Layer, Line, Stage, Text } from 'react-konva'
import { gymApi } from '../api/gym'
import { errorMessage } from '../api/client'
import { RoomShape } from '../components/RoomShape'
import { useConfirm } from '../components/ConfirmDialog'
import type { Gym, Room, RoomDraft, RoomType } from '../types'

const WIDTH=1000, HEIGHT=620
const roomTypes: {value:RoomType,label:string}[]=[{value:'CARDIO',label:'Kardio'},{value:'WEIGHTS',label:'Tegovi'},{value:'GROUP_STUDIO',label:'Grupni studio'},{value:'FUNCTIONAL',label:'Funkcionalni trening'},{value:'LOCKER_ROOM',label:'Svlačionica'},{value:'OTHER',label:'Ostalo'}]
const emptyRoom:RoomDraft={name:'Nova sala',type:'FUNCTIONAL',capacity:10,posX:80,posY:80,width:240,height:150,rotationDegrees:0}
const emptyGym: Omit<Gym, 'id'>={name:'Moja teretana',address:'',phone:'',email:'',logoUrl:null,brandColor:'#BAF252',timezone:'Europe/Belgrade'}

export function EditorPage(){
 const {requestConfirmation,confirmationDialog}=useConfirm()
 const wrap=useRef<HTMLDivElement>(null); const [scale,setScale]=useState(1); const [gym,setGym]=useState<Gym|null>(null); const [rooms,setRooms]=useState<Room[]>([]); const [selected,setSelected]=useState<number|null>(null); const [draft,setDraft]=useState<RoomDraft|null>(null); const [gymDraft,setGymDraft]=useState(emptyGym); const [showGym,setShowGym]=useState(false); const [busy,setBusy]=useState(true); const [notice,setNotice]=useState(''); const [error,setError]=useState('')
 useEffect(()=>{const ro=new ResizeObserver(([e])=>setScale(Math.min(1,e.contentRect.width/WIDTH))); if(wrap.current)ro.observe(wrap.current);return()=>ro.disconnect()},[])
 useEffect(()=>{void load()},[])
 async function load(){setBusy(true);setError('');try{const current=await gymApi.gym();setGym(current);setGymDraft({...current,logoUrl:current.logoUrl??null});setRooms(await gymApi.rooms())}catch(err){if((err as {response?:{status?:number}}).response?.status===404)setShowGym(true);else setError(errorMessage(err))}finally{setBusy(false)}}
 async function saveGym(e:FormEvent){e.preventDefault();setError('');try{const result=gym?await gymApi.updateGym(gym.id,gymDraft):await gymApi.createGym(gymDraft);setGym(result);setShowGym(false);setNotice('Podešavanja teretane su sačuvana.')}catch(err){setError(errorMessage(err))}}
 async function saveRoom(e:FormEvent){e.preventDefault();if(!draft)return;setError('');try{const existing=selected?rooms.find(r=>r.id===selected):null;const result=existing?await gymApi.updateRoom(existing.id,draft):await gymApi.createRoom(draft);setRooms(rs=>existing?rs.map(r=>r.id===result.id?result:r):[...rs,result]);setSelected(result.id);setDraft(null);setNotice(existing?'Sala je ažurirana.':'Sala je dodata na plan.')}catch(err){setError(errorMessage(err))}}
 async function changeRoom(next:Room,persist:boolean){setRooms(rs=>rs.map(r=>r.id===next.id?next:r));if(persist){try{const {id:_,gym:__,...body}=next;const saved=await gymApi.updateRoom(next.id,body);setRooms(rs=>rs.map(r=>r.id===saved.id?saved:r));setNotice('Pozicija je sačuvana.')}catch(err){setError(errorMessage(err));void load()}}}
 async function removeRoom(){if(!selected||!await requestConfirmation({title:'Brisanje sale',message:'Obrisati izabranu salu?',confirmLabel:'Obriši salu'}))return;try{await gymApi.deleteRoom(selected);setRooms(rs=>rs.filter(r=>r.id!==selected));setSelected(null);setDraft(null);setNotice('Sala je obrisana.')}catch(err){setError(errorMessage(err))}}
 const editSelected=()=>{const r=rooms.find(x=>x.id===selected);if(r){const{id:_,gym:__,...body}=r;setDraft(body)}}
 return <main className="workspace-page">{confirmationDialog}
  <header className="workspace-header"><div><p className="eyebrow">Floor plan studio</p><h1>Editor sala</h1><p>Prevucite, rotirajte i prilagodite prostor — svaka izmena se čuva u planu.</p></div><div className="header-actions"><button className="secondary-button" onClick={()=>setShowGym(true)}>⚙ Podešavanja</button><button className="primary-button compact" disabled={!gym} onClick={()=>{setSelected(null);setDraft({...emptyRoom,posX:80+rooms.length*25,posY:80+rooms.length*20})}}>＋ Dodaj salu</button></div></header>
  {error&&<div className="page-alert error" role="alert">{error}</div>}{notice&&<div className="page-alert" onAnimationEnd={()=>setNotice('')}>✓ {notice}</div>}
  <section className="editor-layout">
   <div className="canvas-card"><div className="canvas-toolbar"><span><i/> Plan teretane</span><small>{rooms.length} sala · kliknite za izbor</small></div><div className="canvas-wrap" ref={wrap} style={{height:HEIGHT*scale}}>{busy?<div className="canvas-loading">Učitavanje plana…</div>:<Stage width={WIDTH*scale} height={HEIGHT*scale} scaleX={scale} scaleY={scale} onMouseDown={(e)=>{if(e.target===e.target.getStage())setSelected(null)}}><Layer>{[
     ...Array.from({length:21},(_,i)=><Line key={`v${i}`} points={[i*50,0,i*50,HEIGHT]} stroke="#dfe5dc" strokeWidth={1}/>),
     ...Array.from({length:13},(_,i)=><Line key={`h${i}`} points={[0,i*50,WIDTH,i*50]} stroke="#dfe5dc" strokeWidth={1}/>),
     ...(rooms.length===0?[<Text key="empty" text="Dodajte prvu salu da započnete plan" x={300} y={285} width={400} align="center" fill="#8b968e" fontSize={16}/>]:[]),
     ...rooms.map(room=><RoomShape key={room.id} room={room} selected={selected===room.id} onSelect={()=>setSelected(room.id)} onChange={changeRoom}/>)
   ]}</Layer></Stage>}</div></div>
   <aside className="inspector-card"><p className="eyebrow">Inspektor</p>{selected?(()=>{const r=rooms.find(x=>x.id===selected)!;return <><h2>{r.name}</h2><div className="room-swatch type-functional">{r.type.replace('_',' ')}</div><dl><div><dt>Kapacitet</dt><dd>{r.capacity}</dd></div><div><dt>Pozicija</dt><dd>{Math.round(r.posX)}, {Math.round(r.posY)}</dd></div><div><dt>Dimenzije</dt><dd>{Math.round(r.width)} × {Math.round(r.height)}</dd></div><div><dt>Rotacija</dt><dd>{Math.round(r.rotationDegrees)}°</dd></div></dl><button className="secondary-button wide" onClick={editSelected}>Uredi detalje</button><button className="danger-button wide" onClick={removeRoom}>Obriši salu</button><p className="inspector-tip">Savet: koristite ručke oko izabrane sale za resize i rotaciju.</p></>})():<div className="empty-inspector"><span>⌗</span><h3>Izaberite salu</h3><p>Kliknite na prostor u planu da vidite detalje i opcije.</p></div>}</aside>
  </section>
  {(draft||showGym)&&<div className="modal-backdrop" onMouseDown={()=>{setDraft(null);setShowGym(false)}}><section className="modal" onMouseDown={e=>e.stopPropagation()}>{showGym?<form onSubmit={saveGym}><div className="modal-head"><div><p className="eyebrow">Identitet lokacije</p><h2>Podešavanja teretane</h2></div><button type="button" onClick={()=>setShowGym(false)}>×</button></div><div className="form-grid"><label>Naziv<input required value={gymDraft.name} onChange={e=>setGymDraft({...gymDraft,name:e.target.value})}/></label><label>Adresa<input required value={gymDraft.address} onChange={e=>setGymDraft({...gymDraft,address:e.target.value})}/></label><label>Telefon<input value={gymDraft.phone} onChange={e=>setGymDraft({...gymDraft,phone:e.target.value})}/></label><label>Email<input type="email" value={gymDraft.email} onChange={e=>setGymDraft({...gymDraft,email:e.target.value})}/></label><label>Brend boja<input type="color" value={gymDraft.brandColor} onChange={e=>setGymDraft({...gymDraft,brandColor:e.target.value})}/></label><label>Vremenska zona<input required value={gymDraft.timezone} onChange={e=>setGymDraft({...gymDraft,timezone:e.target.value})}/></label></div><button className="primary-button">Sačuvaj teretanu</button></form>:draft&&<form onSubmit={saveRoom}><div className="modal-head"><div><p className="eyebrow">Prostor u planu</p><h2>{selected?'Uredi salu':'Nova sala'}</h2></div><button type="button" onClick={()=>setDraft(null)}>×</button></div><div className="form-grid"><label>Naziv<input autoFocus required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Tip<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as RoomType})}>{roomTypes.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label>Kapacitet<input required min="1" type="number" value={draft.capacity} onChange={e=>setDraft({...draft,capacity:+e.target.value})}/></label><label>Rotacija<input type="number" min="-180" max="180" value={draft.rotationDegrees} onChange={e=>setDraft({...draft,rotationDegrees:+e.target.value})}/></label><label>Širina<input required min="70" type="number" value={draft.width} onChange={e=>setDraft({...draft,width:+e.target.value})}/></label><label>Visina<input required min="60" type="number" value={draft.height} onChange={e=>setDraft({...draft,height:+e.target.value})}/></label></div><button className="primary-button">Sačuvaj salu</button></form>}</section></div>}
 </main>
}
