import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, Cell, Pie, PieChart, RadialBar, RadialBarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { errorMessage } from '../api/client'
import { insightsApi } from '../api/insights'
import type { InsightRating, ManagerInsight, ManagerMetricInsight } from '../types'

const ratingLabel:Record<InsightRating,string>={EXCELLENT:'Odlično',GOOD:'Dobro',AVERAGE:'Prosečno',POOR:'Potrebna pažnja'}
const ratingColor:Record<InsightRating,string>={EXCELLENT:'#59a52c',GOOD:'#8fbd3f',AVERAGE:'#e2ad3d',POOR:'#df6658'}

function MetricTooltip({active,payload}:{active?:boolean;payload?:Array<{payload:ManagerMetricInsight}>}){
 const metric=payload?.[0]?.payload
 return active&&metric?<div className="insight-tooltip"><strong>{metric.label}</strong><span>{metric.value.toLocaleString('sr-RS')} {metric.unit}</span><small style={{color:ratingColor[metric.rating]}}>{ratingLabel[metric.rating]}</small></div>:null
}

export function ManagerInsightsPage(){
 const[insight,setInsight]=useState<ManagerInsight|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 const load=async(force=false)=>{setLoading(true);setError('');try{setInsight(await insightsApi.manager(force))}catch(reason){setError(errorMessage(reason))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const groups=useMemo(()=>{const metrics=insight?.metrics??[];return{rooms:metrics.filter(metric=>metric.key.startsWith('room-')),individual:metrics.find(metric=>metric.key==='individual-mix'),group:metrics.find(metric=>metric.key==='group-mix'),attendance:metrics.find(metric=>metric.key==='attendance'),sold:metrics.find(metric=>metric.key==='sold-units')}},[insight])
 const mix=[groups.individual,groups.group].filter((metric):metric is ManagerMetricInsight=>Boolean(metric))
 const ratingCounts=insight?(['EXCELLENT','GOOD','AVERAGE','POOR'] as InsightRating[]).map(rating=>({rating,count:insight.metrics.filter(metric=>metric.rating===rating).length})):[]
 return <main className="workspace-page insights-page insights-dashboard">
  <header className="workspace-header"><div><p className="eyebrow">Poslovni puls · poslednjih 30 dana</p><h1>AI uvidi</h1><p>Jedan pogled na kapacitete, ponudu, posećenost i prodaju.</p></div><button className="primary-button compact" disabled={loading} onClick={()=>void load(true)}>{loading?'Analiziram…':'↻ Osveži analizu'}</button></header>
  {error&&<div className="content-error">{error}<button onClick={()=>void load()}>Pokušaj ponovo</button></div>}
  {loading&&!insight?<section className="insight-hero"><div className="insight-skeleton"><i/><i/><i/></div></section>:insight&&<>
   <section className="insight-command-center"><div className="insight-narrative"><div className="ai-spark">✦</div><p className="eyebrow">AI izvršni rezime</p><h2>{insight.summary}</h2><div className="insight-generated">Ažurirano {new Date(insight.generatedAt).toLocaleString('sr-RS')} · {insight.model}</div><div className="rating-overview">{ratingCounts.map(item=><span key={item.rating} style={{'--rating':ratingColor[item.rating]} as React.CSSProperties}><i/>{item.count} {ratingLabel[item.rating]}</span>)}</div></div><aside className="insight-actions"><p className="eyebrow">Šta uraditi sledeće</p><ol>{insight.recommendations.map((recommendation,index)=><li key={index}><span>{index+1}</span><p>{recommendation}</p></li>)}</ol></aside></section>
   <section className="insight-chart-grid">
    <article className="insight-chart-card room-performance"><div className="chart-title"><div><p className="eyebrow">Kapaciteti uživo</p><h2>Zauzetost sala</h2></div><span>trenutno</span></div><div className="chart-frame room-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={groups.rooms} layout="vertical" margin={{left:4,right:24}}><XAxis type="number" domain={[0,100]} hide/><YAxis type="category" dataKey="label" width={145} tickFormatter={value=>String(value).replace('Popunjenost · ','')} tick={{fontSize:11,fill:'#68756c'}} axisLine={false} tickLine={false}/><Tooltip content={<MetricTooltip/>}/><Bar dataKey="value" radius={[0,8,8,0]} background={{fill:'#edf2eb',radius:8}}>{groups.rooms.map(metric=><Cell key={metric.key} fill={ratingColor[metric.rating]}/>)}</Bar></BarChart></ResponsiveContainer></div></article>
    <article className="insight-chart-card mix-performance"><div className="chart-title"><div><p className="eyebrow">Portfolio treninga</p><h2>Individualno ili grupno</h2></div></div><div className="donut-layout"><div className="chart-frame donut-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={mix} dataKey="value" nameKey="label" innerRadius={58} outerRadius={86} paddingAngle={4} stroke="none">{mix.map(metric=><Cell key={metric.key} fill={ratingColor[metric.rating]}/>)}</Pie><Tooltip content={<MetricTooltip/>}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>100%</strong><span>sesija</span></div></div><div className="chart-legend">{mix.map(metric=><div key={metric.key}><i style={{background:ratingColor[metric.rating]}}/><span>{metric.key==='individual-mix'?'Individualni':'Grupni'}</span><strong>{metric.value}%</strong></div>)}</div></div></article>
    {groups.attendance&&<article className="insight-chart-card attendance-performance" style={{'--rating':ratingColor[groups.attendance.rating]} as React.CSSProperties}><div className="chart-title"><div><p className="eyebrow">Realizacija rezervacija</p><h2>Posećenost</h2></div><span className={`rating-badge ${groups.attendance.rating.toLowerCase()}`}>{ratingLabel[groups.attendance.rating]}</span></div><div className="attendance-layout"><div className="chart-frame attendance-chart"><ResponsiveContainer width="100%" height="100%"><RadialBarChart innerRadius="72%" outerRadius="100%" data={[groups.attendance]} startAngle={210} endAngle={-30}><RadialBar dataKey="value" cornerRadius={12} fill={ratingColor[groups.attendance.rating]} background={{fill:'#edf2eb'}}/></RadialBarChart></ResponsiveContainer><div className="gauge-value"><strong>{groups.attendance.value}%</strong><span>check-in / rezervacije</span></div></div><p>{groups.attendance.comment}</p></div></article>}
    {groups.sold&&<article className="insight-chart-card sold-performance" style={{'--rating':ratingColor[groups.sold.rating]} as React.CSSProperties}><div className="chart-title"><div><p className="eyebrow">Prodajni rezultat</p><h2>Plaćeni termini</h2></div><span className={`rating-badge ${groups.sold.rating.toLowerCase()}`}>{ratingLabel[groups.sold.rating]}</span></div><div className="sold-value"><span>¤</span><strong>{groups.sold.value.toLocaleString('sr-RS')}</strong><small>{groups.sold.unit} u periodu</small></div><p>{groups.sold.comment}</p></article>}
   </section>
   <section className="insight-detail-section"><div className="section-heading"><div><p className="eyebrow">Dijagnostika</p><h2>Svaki pokazatelj, jasno ocenjen</h2></div><p>Boja linije i skale direktno prati AI ocenu.</p></div><div className="insight-metric-grid">{insight.metrics.map(metric=><article className="insight-metric" key={metric.key} style={{'--rating':ratingColor[metric.rating]} as React.CSSProperties}><div className="metric-accent"/><div className="card-head"><h3>{metric.label}</h3><span className={`rating-badge ${metric.rating.toLowerCase()}`}>{ratingLabel[metric.rating]}</span></div><strong>{metric.value.toLocaleString('sr-RS')} <small>{metric.unit}</small></strong><div className="metric-visual"><i style={{width:`${metric.unit==='%'?Math.min(100,Math.max(0,metric.value)):100}%`}}/></div><p>{metric.comment}</p></article>)}</div></section>
  </>}
  <p className="ai-disclaimer">Brojevi su izračunati iz baze; AI daje samo ocenu i preporuku. Važne odluke proverite u izvornim podacima.</p>
 </main>
}
