import { useEffect, useState } from 'react'
import { appointmentsApi } from '../api/appointments'
import { errorMessage } from '../api/client'
import { clientsApi, trainersApi } from '../api/administration'
import { gymApi } from '../api/gym'
import { calendarApi } from '../api/operations'
import type { AppointmentSummary, ClientProfile, Room, SessionInfo, TrainerProfile } from '../types'

const today=()=>{const date=new Date();date.setDate(date.getDate()+1);return date.toISOString().slice(0,10)}
export function ManagerAppointmentsPage(){
 const [date,setDate]=useState(today());const [items,setItems]=useState<AppointmentSummary[]>([]);const [sessions,setSessions]=useState<SessionInfo[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [trainers,setTrainers]=useState<TrainerProfile[]>([]);const [clients,setClients]=useState<ClientProfile[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const [form,setForm]=useState({startTime:'09:00',endTime:'10:00',sessionId:'',roomId:'',trainerId:''})
 const loadDay=()=>calendarApi.day(date).then(r=>setItems(r.appointments))
 useEffect(()=>{Promise.all([appointmentsApi.sessions(),gymApi.rooms(),trainersApi.list(),clientsApi.list()]).then(([s,r,t,c])=>{setSessions(s);setRooms(r);setTrainers(t);setClients(c);setForm(f=>({...f,sessionId:f.sessionId||String(s[0]?.id??'')}))}).catch(e=>setError(errorMessage(e)))},[])
 useEffect(()=>{loadDay().catch(e=>setError(errorMessage(e)))},[date])
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await loadDay()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const create=()=>void run(()=>appointmentsApi.create({date,startTime:`${form.startTime}:00`,endTime:`${form.endTime}:00`,sessionId:Number(form.sessionId),roomId:form.roomId?Number(form.roomId):undefined,trainerId:form.trainerId?Number(form.trainerId):undefined,clientIds:[]}))
 return <main className="workspace-page manager-appointments"><header className="workspace-header"><div><p className="eyebrow">Operativno planiranje</p><h1>Upravljanje terminima</h1><p>Kreirajte slot, dodelite trenera i upravljajte učesnicima.</p></div><label className="date-filter">Datum<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></header>{error&&<div className="content-error">{error}</div>}
 <section className="schedule-layout"><form className="operation-card appointment-create" onSubmit={create}><div className="card-head"><div><p className="eyebrow">Novi slot</p><h2>Kreiraj termin</h2></div></div><div className="form-grid"><label>Početak<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} required/></label><label>Kraj<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} required/></label><label>Tip sesije<select value={form.sessionId} onChange={e=>setForm({...form,sessionId:e.target.value})} required>{sessions.map(s=><option key={s.id} value={s.id}>{s.type==='INDIVIDUAL'?'Individualni':'Grupni'} · {s.maxParticipants} mesta</option>)}</select></label><label>Soba<select value={form.roomId} onChange={e=>setForm({...form,roomId:e.target.value})}><option value="">Bez sobe</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="span-two">Trener (opciono)<select value={form.trainerId} onChange={e=>setForm({...form,trainerId:e.target.value})}><option value="">Nedodeljen</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.user.email}</option>)}</select></label></div><button className="primary-button" disabled={busy}>Kreiraj termin</button></form>
 <section className="operation-card appointment-roster"><div className="card-head"><div><p className="eyebrow">{date}</p><h2>Termini tog dana</h2></div><strong>{items.length}</strong></div>{items.length===0?<div className="empty-panel">Nema termina za izabrani datum.</div>:items.map(a=><article className="manager-appointment-row" key={a.id}><div className="appointment-row-head"><strong>{a.startTime.slice(0,5)}–{a.endTime.slice(0,5)}</strong><span>{a.session.type==='INDIVIDUAL'?'Individualni':'Grupni'} · {a.room?.name??'bez sobe'}</span></div><label>Trener<select value={a.trainer?.id??''} disabled={busy} onChange={e=>void run(()=>e.target.value?appointmentsApi.addTrainer(a.id,Number(e.target.value)):appointmentsApi.removeTrainer(a.id))}><option value="">Nedodeljen</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.user.email}</option>)}</select></label><div className="roster-list">{a.clients.map(c=><span key={c.id}>{c.email}<button title="Ukloni klijenta" onClick={()=>void run(()=>appointmentsApi.removeClient(a.id,c.id))}>×</button></span>)}</div><label>Dodaj klijenta<select defaultValue="" disabled={busy||a.clients.length>=a.session.maxParticipants} onChange={e=>{if(e.target.value){void run(()=>appointmentsApi.addClients(a.id,[Number(e.target.value)]));e.target.value=''}}}><option value="">Izaberite klijenta…</option>{clients.filter(c=>!a.clients.some(x=>x.id===c.id)).map(c=><option key={c.id} value={c.id}>{c.user.email}</option>)}</select></label></article>)}</section></section></main>
}
