import { useEffect, useState } from 'react'
import { appointmentsApi } from '../api/appointments'
import { errorMessage } from '../api/client'
import { clientsApi, trainersApi } from '../api/administration'
import { gymApi } from '../api/gym'
import { calendarApi } from '../api/operations'
import { MonthCalendar } from '../components/MonthCalendar'
import type { AppointmentSummary, ClientProfile, Room, SessionInfo, TrainerProfile } from '../types'
import { gymScheduleApi, holidayApi } from '../api/schedules'
import { gymClosure, isGymClosed } from '../utils/gymAvailability'

const tomorrow=()=>{const value=new Date();value.setDate(value.getDate()+1);return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`}

export function ManagerAppointmentsPage(){
 const [date,setDate]=useState(tomorrow());const [items,setItems]=useState<AppointmentSummary[]>([]);const [sessions,setSessions]=useState<SessionInfo[]>([]);const [rooms,setRooms]=useState<Room[]>([]);const [trainers,setTrainers]=useState<TrainerProfile[]>([]);const [clients,setClients]=useState<ClientProfile[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [recurring,setRecurring]=useState(false)
 const [form,setForm]=useState({startTime:'09:00',endTime:'10:00',sessionId:'',roomId:'',trainerId:''})
 const [closure,setClosure]=useState({mutedDates:new Set<string>(),mutedWeekdays:new Set<number>()})
 const loadDay=()=>calendarApi.day(date).then(result=>setItems(result.appointments))
 useEffect(()=>{Promise.all([appointmentsApi.sessions(),gymApi.rooms(),trainersApi.list(),clientsApi.list(),gymScheduleApi.list(),holidayApi.list()]).then(([sessionRows,roomRows,trainerRows,clientRows,schedules,holidays])=>{setSessions(sessionRows);setRooms(roomRows);setTrainers(trainerRows);setClients(clientRows);setClosure(gymClosure(schedules,holidays));setForm(current=>({...current,sessionId:current.sessionId||String(sessionRows[0]?.id??''),roomId:current.roomId||String(roomRows[0]?.id??'')}))}).catch(reason=>setError(errorMessage(reason)))},[])
 useEffect(()=>{loadDay().catch(reason=>setError(errorMessage(reason)))},[date])
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await loadDay()}catch(reason){setError(errorMessage(reason))}finally{setBusy(false)}}
 const create=(event:React.FormEvent)=>{event.preventDefault();const input={date,startTime:`${form.startTime}:00`,endTime:`${form.endTime}:00`,sessionId:Number(form.sessionId),roomId:Number(form.roomId),trainerId:form.trainerId?Number(form.trainerId):undefined,clientIds:[]};void run(async()=>{if(recurring){const result=await appointmentsApi.createRecurring(input);setNotice(`Kreirano termina: ${result.createdCount}${result.skippedReasons.length?` · Preskočeno: ${result.skippedReasons.length}`:''}`)}else{await appointmentsApi.create(input);setNotice('Termin je kreiran.')}})}
 const gymClosed=isGymClosed(date,closure.mutedDates,closure.mutedWeekdays)
 return <main className="workspace-page manager-appointments">
  <header className="workspace-header"><div><p className="eyebrow">Operativno planiranje</p><h1>Upravljanje terminima</h1><p>Kreirajte slot, dodelite trenera i upravljajte učesnicima.</p></div></header>
  {error&&<div className="content-error">{error}</div>}{notice&&<div className="content-success">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <div className="calendar-list-layout">
   <MonthCalendar value={date} onChange={setDate} highlightedDates={new Set(items.map(item=>item.date))} mutedDates={closure.mutedDates} mutedWeekdays={closure.mutedWeekdays}/>
   <section className="schedule-layout">
    <form className="operation-card appointment-create" onSubmit={create}><div className="card-head"><div><p className="eyebrow">Novi slot</p><h2>Kreiraj termin</h2></div></div><div className="form-grid"><label>Početak<input type="time" value={form.startTime} onChange={event=>setForm({...form,startTime:event.target.value})} required/></label><label>Kraj<input type="time" value={form.endTime} onChange={event=>setForm({...form,endTime:event.target.value})} required/></label><label>Tip sesije<select value={form.sessionId} onChange={event=>setForm({...form,sessionId:event.target.value})} required>{sessions.map(session=><option key={session.id} value={session.id}>{session.type==='INDIVIDUAL'?'Individualni':'Grupni'} · {session.maxParticipants} mesta</option>)}</select></label><label>Soba<select value={form.roomId} onChange={event=>setForm({...form,roomId:event.target.value})} required>{rooms.map(room=><option key={room.id} value={room.id}>{room.name}</option>)}</select></label><label className="span-two">Trener (opciono)<select value={form.trainerId} onChange={event=>setForm({...form,trainerId:event.target.value})}><option value="">Nedodeljen</option>{trainers.map(trainer=><option key={trainer.id} value={trainer.id}>{trainer.user.email}</option>)}</select></label><label className="span-two recurring-choice"><input type="checkbox" checked={recurring} onChange={event=>setRecurring(event.target.checked)}/> Fiksni termin (8 nedelja)</label></div>{gymClosed&&<div className="empty-panel">Teretana ne radi izabranog dana. Kreiranje termina nije dostupno.</div>}<button className="primary-button" disabled={busy||gymClosed}>Kreiraj termin</button></form>
    <section className="operation-card appointment-roster"><div className="card-head"><div><p className="eyebrow">{date}</p><h2>Termini tog dana</h2></div><strong>{items.length}</strong></div>{items.length===0?<div className="empty-panel">Nema termina za izabrani datum.</div>:items.map(appointment=><article className="manager-appointment-row" key={appointment.id}><div className="appointment-row-head"><strong>{appointment.startTime.slice(0,5)}–{appointment.endTime.slice(0,5)}</strong><span>{appointment.session.type==='INDIVIDUAL'?'Individualni':'Grupni'} · {appointment.room?.name??'bez sobe'}</span></div><label>Trener<select value={appointment.trainer?.id??''} disabled={busy} onChange={event=>void run(()=>event.target.value?appointmentsApi.addTrainer(appointment.id,Number(event.target.value)):appointmentsApi.removeTrainer(appointment.id))}><option value="">Nedodeljen</option>{trainers.map(trainer=><option key={trainer.id} value={trainer.id}>{trainer.user.email}</option>)}</select></label><div className="roster-list">{appointment.clients.map(client=><span key={client.id}>{client.email}<button title="Ukloni klijenta" onClick={()=>void run(()=>appointmentsApi.removeClient(appointment.id,client.id))}>×</button></span>)}</div><label>Dodaj klijenta<select defaultValue="" disabled={busy||appointment.clients.length>=appointment.session.maxParticipants} onChange={event=>{if(event.target.value){void run(()=>appointmentsApi.addClients(appointment.id,[Number(event.target.value)]));event.target.value=''}}}><option value="">Izaberite klijenta…</option>{clients.filter(client=>!appointment.clients.some(existing=>existing.id===client.id)).map(client=><option key={client.id} value={client.id}>{client.user.email}</option>)}</select></label></article>)}</section>
   </section>
  </div>
 </main>
}
