spring:
  application:
    name: fitness-manager

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:8877/fm
    username: fm_dbuser
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
#      password: podesi password i na docker-compose, sad je bez passworda

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: cedajuric@gmail.com
    password: juriccedakrivogleda
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8088

app:
  registration-key-validity-minutes: 10
  reset-key-validity-minutes: 10

  jwt:
    expiration: 3600
    secret: ThisIsAVeryStrongSecretKeyWithEnoughLength